### ISSUE TITLE
MathJax: "inline" appears like "display"

### ISSUE THREAD

**Issue by akobler** [mjpost/nvalt-files#1]
Hi

Thanks a lot for your nvALT-files.
I'd like to insert inline MathJax. But when using $$...$$ (as configured in https://github.com/mjpost/nvalt-files/blob/master/template.html), the formula appears as it does in "display" mode (inserted with \\[...\\]). Do you encounter the same behaviour or can you give me a hint what I might miss?

Many thanks, Andi

**Comment by akobler** [comment]
MathJax configuration in template.html:
```
  MathJax.Hub.Config({
    tex2jax: {inlineMath: [['$$','$$']], displayMath: [['\\(','\\)'], ['\\[','\\]']]}
  });
```

When writing the  note:
```
When $$a \ne 0$$, there are two solutions.
```

The following HTML is created. Already here, the `$$` is replaced by `\[`.
```HTML
<p>When <span class="math">\[a \ne 0\]</span>, there are two solutions.</p>
```

**Comment by akobler** [comment]
It was a configuration issue. It seems that `$$` cannot be reconfigured to `inlineMath`. If I use other symbols for `inlineMath`, it works. 

Sorry for the noise.

**Comment by mjpost** [comment]
No worries! Glad you figured it out, and thanks for posting the followup.
